'use client';
import { useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase-browser';

type Post={id?:string;titulo:string;slug:string;tipo:string;area:string;resumen:string;contenido:string;imagen_url?:string;publicado?:boolean;fecha?:string};
const empty:Post={titulo:'',slug:'',tipo:'jurisprudencia',area:'',resumen:'',contenido:'',imagen_url:'',publicado:true};
export default function Admin(){const [session,setSession]=useState<any>(null); const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [posts,setPosts]=useState<Post[]>([]);const [form,setForm]=useState<Post>(empty);const [msg,setMsg]=useState(''); const supabase=createClient();
useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));supabase.auth.onAuthStateChange((_e,s)=>setSession(s));},[]);
async function login(e:any){e.preventDefault();const {error}=await supabase.auth.signInWithPassword({email,password});setMsg(error?.message||'Sesión iniciada.');}
async function load(){const {data}=await supabase.from('publicaciones').select('*').order('fecha',{ascending:false});setPosts(data||[])}
useEffect(()=>{if(session)load()},[session]);
function edit(p:Post){setForm(p);window.scrollTo({top:0,behavior:'smooth'})}
async function save(e:any){e.preventDefault();const payload={...form,slug:form.slug||form.titulo.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')};const q=form.id?supabase.from('publicaciones').update(payload).eq('id',form.id):supabase.from('publicaciones').insert(payload);const {error}=await q;setMsg(error?.message||'Publicación guardada.');if(!error){setForm(empty);load()}}
async function del(id:string){if(!confirm('¿Eliminar publicación?'))return;await supabase.from('publicaciones').delete().eq('id',id);load()}
if(!session)return <main className="admin-page"><div className="login-card"><div className="eyebrow">PABLO RIMACHI_JURIS</div><h1>Panel editorial</h1><p>Ingresa para crear y administrar tus publicaciones.</p><form onSubmit={login}><input placeholder="Correo" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><input placeholder="Contraseña" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/><button className="button primary">Ingresar</button></form>{msg&&<small>{msg}</small>}</div></main>;
return <main className="admin-page"><div className="container admin-grid"><section className="editor"><div className="section-head"><div><div className="eyebrow">EDITOR</div><h1>{form.id?'Editar publicación':'Nueva publicación'}</h1></div><button className="button secondary" onClick={()=>supabase.auth.signOut()}>Cerrar sesión</button></div><form onSubmit={save}><label>Título<input value={form.titulo} onChange={e=>setForm({...form,titulo:e.target.value})} required/></label><label>Tipo<select value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})}><option value="jurisprudencia">Jurisprudencia</option><option value="doctrina">Doctrina</option><option value="normativa">Normativa</option></select></label><label>Área<input value={form.area} onChange={e=>setForm({...form,area:e.target.value})} placeholder="Laboral, ambiental, penal..."/></label><label>Resumen<textarea value={form.resumen} onChange={e=>setForm({...form,resumen:e.target.value})} rows={3} required/></label><label>Imagen de portada (URL)<input value={form.imagen_url||''} onChange={e=>setForm({...form,imagen_url:e.target.value})} placeholder="https://..."/></label><label>Contenido<textarea value={form.contenido} onChange={e=>setForm({...form,contenido:e.target.value})} rows={14} required/></label><label className="check"><input type="checkbox" checked={!!form.publicado} onChange={e=>setForm({...form,publicado:e.target.checked})}/> Publicar</label><button className="button primary">{form.id?'Actualizar':'Publicar'} contenido</button>{msg&&<span className="msg">{msg}</span>}</form></section><aside className="admin-list"><h2>Publicaciones</h2>{posts.map(p=><div className="admin-item" key={p.id}><div><span className={`type-tag ${p.tipo}`}>{p.tipo}</span><b>{p.titulo}</b></div><div><button onClick={()=>edit(p)}>Editar</button><button onClick={()=>del(p.id!)}>Eliminar</button></div></div>)}</aside></div></main>}
