import Link from 'next/link';
import { getPosts } from '@/lib/posts';

export default async function Home({ searchParams }: { searchParams: Promise<{tipo?: string; q?: string}> }) {
  const params = await searchParams; const posts = await getPosts(params.tipo, params.q);
  return <main>
    <section className="hero"><div className="container hero-grid"><div><div className="eyebrow">PABLO RIMACHI · JURIS</div><h1>Derecho <em>analizado</em>, explicado y ordenado.</h1><p className="lead">Una plataforma personal para convertir jurisprudencia, doctrina y normativa en contenido jurídico claro, útil y listo para compartir.</p><div className="hero-actions"><Link href="#publicaciones" className="button primary">Explorar publicaciones</Link><Link href="/admin" className="button secondary">Publicar análisis</Link></div></div><div className="hero-card"><div className="hero-card-top">ARCHIVO JURÍDICO</div><div className="hero-stat"><strong>03</strong><span>líneas editoriales</span></div><div className="mini-list"><span>01 · Jurisprudencia</span><span>02 · Doctrina</span><span>03 · Normativa</span></div></div></div></section>
    <section className="container editorial-strip"><div><b>Una publicación, una idea central.</b><span> Cada entrada está diseñada para lectura rápida y difusión profesional.</span></div><Link href="/admin">+ Nueva publicación</Link></section>
    <section id="publicaciones" className="container content-section"><div className="section-head"><div><div className="eyebrow">BIBLIOTECA</div><h2>Últimas publicaciones</h2></div><div className="filters"><Link href="/">Todas</Link><Link href="/?tipo=jurisprudencia">Jurisprudencia</Link><Link href="/?tipo=doctrina">Doctrina</Link><Link href="/?tipo=normativa">Normativa</Link></div></div>{posts.length === 0 ? <div className="empty">No hay publicaciones con esos criterios.</div> : <div className="post-grid">{posts.map(p => <Link className="post-card" href={`/publicacion/${p.slug}`} key={p.id}><div className={`type-tag ${p.tipo}`}>{p.tipo}</div><h3>{p.titulo}</h3><p>{p.resumen}</p><div className="card-meta"><span>{p.area || 'Derecho'}</span><span>{new Date(p.fecha).toLocaleDateString('es-PE',{year:'numeric',month:'short',day:'numeric'})}</span></div></Link>)}</div>}</section>
    <section className="container manifesto"><div className="manifesto-number">/</div><div><div className="eyebrow">CRITERIO EDITORIAL</div><h2>Menos ruido. Más estructura.</h2><p>Cada contenido separa hechos, norma, criterio jurídico, discusión y conclusión para facilitar su lectura y reutilización en contextos profesionales.</p></div></section>
  </main>
}
